### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by madaz** [lud2k/ts-react-display-name#6]
Getting the following error when combing lots of react components in a single file.

Have a PR for the fix.

```
TypeError: Cannot read property 'text' of undefined
    at IdentifierObject.TokenOrIdentifierObject.getText (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:130339:31)
    at c:\[obsufacted]\node_modules\ts-react-display-name\dist\index.js:51:29
    at Array.find (<anonymous>)
    at isStaticDisplayNameDefined (c:\[obsufacted]\node_modules\ts-react-display-name\dist\index.js:47:38)
    at visitor (c:\[obsufacted]\node_modules\ts-react-display-name\dist\index.js:88:18)
    at visitNodes (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:70998:48)
    at visitLexicalEnvironment (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:71031:22)
    at Object.visitEachChild (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:71344:54)
    at visitor (c:\[obsufacted]\node_modules\ts-react-display-name\dist\index.js:95:23)
    at Object.visitNode (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:70947:23)
    at c:\[obsufacted]\node_modules\ts-react-display-name\dist\index.js:114:27
    at transformSourceFileOrBundle (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:72535:57)
    at transformation (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89317:24)
    at transformRoot (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89337:82)
    at Object.map (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:543:29)
    at Object.transformNodes (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89324:30)
    at emitJsFileOrBundle (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89858:32)
    at emitSourceFileOrBundle (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89811:13)
    at forEachEmittedFile (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89563:34)
    at Object.emitFiles (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:89792:9)
    at emitWorker (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:95809:33)
    at c:\[obsufacted]\node_modules\typescript\lib\typescript.js:95770:66
    at runWithCancellationToken (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:95861:24)
    at Object.emit (c:\[obsufacted]\node_modules\typescript\lib\typescript.js:95770:20)
    at Object.getEmitOutput (c:\[obsufacted]\node_modules\ts-loader\dist\instances.js:361:21)
    at provideDeclarationFilesToWebpack (c:\[obsufacted]\node_modules\ts-loader\dist\after-compile.js:185:41)
    at c:\[obsufacted]\node_modules\ts-loader\dist\after-compile.js:24:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\[obsufacted]\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:5:1)
    at AsyncSeriesHook.lazyCompileHook (c:\[obsufacted]\node_modules\tapable\lib\Hook.js:154:20)
    at c:\[obsufacted]\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\[obsufacted]\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (c:\[obsufacted]\node_modules\tapable\lib\Hook.js:154:20)
    at c:\[obsufacted]\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\[obsufacted]\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (c:\[obsufacted]\node_modules\tapable\lib\Hook.js:154:20)
    at c:\[obsufacted]\node_modules\webpack\lib\Compilation.js:1414:32
```

**Comment by lud2k** [comment]
Thanks for the PR 👍!
